version: '3'
networks:
  network:

services:
  core:
    container_name: core
    build:
      context: .
      dockerfile: ./core/Dockerfile
    ports:
      - "7888:7888"
      - "7887:7887"
      - "3213:3213"
    volumes:
      - ./logs/chat:/var/log/chat
      - ./file/chat:/var/file/chat
      - ./core/etc/core-api.yaml:/etc/core-api.yaml
    privileged: true
    restart: always
    depends_on:
      - "mysql"
      - "redis"
      - "jaeger"
    networks:
      - network
  redis:
    container_name: chat-redis7
    image: redis:7
    ports:
      - "36379:6379"
    volumes:
      - ./build/redis/redis.conf:/etc/redis/redis.conf
      - ./build/redis/data:/data
    environment:
      TZ: Asia/Shanghai
    networks:
      - network
    restart: always
    command: redis-server /etc/redis/redis.conf
  mysql:
    container_name: chat-mysql57
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "33306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'chat'
      MYSQL_USER: 'chat'
      MYSQL_PASSWORD: '123456'
    volumes:
      - ./build/mysql/data:/var/lib/mysql
      - ./build/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - network
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: chat-jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: always
    networks:
      - network