CREATE TABLE `apple_pay_subscription` (
                                          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                                          `user_id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'user id',
                                          `original_transaction_id` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '原始订阅唯一标识',
                                          `original_receipt` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '原始票据',
                                          `receipt` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '上一次的票据',
                                          `transaction_id` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '每一期的唯一标识',
                                          `order_id` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '订单 id 对应 rights 表 rights_id',
                                          `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '订阅中,订阅关闭',
                                          `renew_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '续费:扣费成功,等待扣费,扣费失败',
                                          `original_product_id` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '一开始订阅的商品 id',
                                          `product_id` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '现在订阅的商品 id',
                                          `expires_date` timestamp NULL DEFAULT NULL COMMENT '订阅周期过期时间',
                                          `purchase_date` timestamp NULL DEFAULT NULL COMMENT '订单周期开始时间 ',
                                          `transaction_reason` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
                                          `transaction_type` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
                                          `in_app_ownership_type` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
                                          `price` int(20) NOT NULL DEFAULT '0',
                                          `currency` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
                                          `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                                          `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                          `is_deleted` tinyint(4) NOT NULL DEFAULT '0',
                                          PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci