// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	customerPromptFieldNames          = builder.RawFieldNames(&CustomerPrompt{})
	customerPromptRows                = strings.Join(customerPromptFieldNames, ",")
	customerPromptRowsExpectAutoSet   = strings.Join(stringx.Remove(customerPromptFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	customerPromptRowsWithPlaceHolder = strings.Join(stringx.Remove(customerPromptFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCustomerPromptIdPrefix = "cache:customerPrompt:id:"
)

type (
	customerPromptModel interface {
		Insert(ctx context.Context, data *CustomerPrompt) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CustomerPrompt, error)
		Update(ctx context.Context, data *CustomerPrompt) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCustomerPromptModel struct {
		sqlc.CachedConn
		table string
	}

	CustomerPrompt struct {
		Id     int64  `db:"id"`
		KfName string `db:"kf_name"`
		KfId   string `db:"kf_id"`
		Prompt string `db:"prompt"`
	}
)

func newCustomerPromptModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCustomerPromptModel {
	return &defaultCustomerPromptModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`customer_prompt`",
	}
}

func (m *defaultCustomerPromptModel) Delete(ctx context.Context, id int64) error {
	customerPromptIdKey := fmt.Sprintf("%s%v", cacheCustomerPromptIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, customerPromptIdKey)
	return err
}

func (m *defaultCustomerPromptModel) FindOne(ctx context.Context, id int64) (*CustomerPrompt, error) {
	customerPromptIdKey := fmt.Sprintf("%s%v", cacheCustomerPromptIdPrefix, id)
	var resp CustomerPrompt
	err := m.QueryRowCtx(ctx, &resp, customerPromptIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", customerPromptRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerPromptModel) Insert(ctx context.Context, data *CustomerPrompt) (sql.Result, error) {
	customerPromptIdKey := fmt.Sprintf("%s%v", cacheCustomerPromptIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, customerPromptRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.KfName, data.KfId, data.Prompt)
	}, customerPromptIdKey)
	return ret, err
}

func (m *defaultCustomerPromptModel) Update(ctx context.Context, data *CustomerPrompt) error {
	customerPromptIdKey := fmt.Sprintf("%s%v", cacheCustomerPromptIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, customerPromptRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.KfName, data.KfId, data.Prompt, data.Id)
	}, customerPromptIdKey)
	return err
}

func (m *defaultCustomerPromptModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCustomerPromptIdPrefix, primary)
}

func (m *defaultCustomerPromptModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", customerPromptRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCustomerPromptModel) tableName() string {
	return m.table
}
