create table if not exists `wechat_user` (
                               `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                               `user` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '微信客户的external_userid',
                               `user_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '用户类型：1,微信用户；2,访客用户',
                               `nickname` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '微信昵称',
                               `avatar` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '微信头像',
                               `gender` tinyint(4) NOT NULL DEFAULT '0' COMMENT '性别',
                               `unionid` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'unionid，需要绑定微信开发者帐号才能获取到',
                               `name` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '姓名',
                               `mobile` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '手机号',
                               `password` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '密码',
                               `constellation` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '星座',
                               `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态（1:启用状态 10删除）',
                               `salt` char(4) CHARACTER SET utf8mb4 NOT NULL COMMENT '盐值',
                               `birthday` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '生日',
                               `openid` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'openid',
                               `country` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'country',
                               `city` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'city',
                               `province` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'province',
                               `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                               `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                               `is_login_free` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否保存30天登录（1:是 0否）',
                               `level` tinyint(4) NOT NULL DEFAULT '0' COMMENT '等级，1vip',
                               `level_expire` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '等级过期时间',
                               `mbti` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'mbti',
                               `is_deleted` tinyint(4) NOT NULL DEFAULT '0',
                               PRIMARY KEY (`id`),
                               KEY `idx_nickname` (`nickname`) USING BTREE,
                               KEY `idx_user` (`user`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=459 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
