version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "8887:8887"
      - "3213:3213"
    volumes:
      - ./logs/web:/var/log/chatgpt-wechat
      - ./service/chat/api/etc/chat-api.yaml:/etc/chat-api.yaml
    privileged: true
    restart: always
    networks:
      - chat_network
  redis:
    container_name: redis7
    image: redis:7
    ports:
      - "46379:6379"
    volumes:
      - ./build/redis/redis.conf:/etc/redis/redis.conf
      - ./build/redis/data:/data
    environment:
      TZ: Asia/Shanghai
    networks:
      - chat_network
    restart: always
    command: redis-server /etc/redis/redis.conf
  mysql:
    container_name: mysql57
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "43306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'chat'
      MYSQL_USER: 'chat'
      MYSQL_PASSWORD: '123456'
    volumes:
      - ./build/mysql/data:/var/lib/mysql
      - ./build/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - chat_network
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./build/etcd/data:/etcd
    networks:
      - chat_network
    restart: always
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./build/minio/data:/minio_data
    networks:
      - chat_network
    restart: always
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.6
    platform: linux/x86_64
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./build/milvus:/var/lib/milvus
      - ./milvus.yaml:/milvus/configs/milvus.yaml
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - chat_network
    restart: always
networks:
  chat_network: