// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	frontend "core/internal/handler/frontend"
	"core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessLog},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/chat",
					Handler: frontend.ChatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/chat/customer",
					Handler: frontend.CustomerChatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/chat/wechat",
					Handler: frontend.WechatChatHandler(serverCtx),
				},
			}...,
		),
	)
}
