// Code generated by goctl. DO NOT EDIT.
package types

type ScriptResponse struct {
	Message string `json:"message"`
}

type ScriptRequest struct {
}

type UploadScriptRequest struct {
}

type UploadScriptResponse struct {
	Message string `json:"message"`
}
