// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"cron/cron/internal/logic"
	"cron/cron/internal/svc"

	"github.com/zeromicro/go-zero/rest"

	"github.com/robfig/cron/v3"

)

func RegisterCrontabs(server *rest.Server, serverCtx *svc.ServiceContext) {
	c := cron.New()
	// 跑脚步 每十分钟一次
	//c.AddFunc("*/10 * * * *", func(svcCtx *svc.ServiceContext) func() {
	//	return func() {
	//		logic.NewCronLogic(svcCtx).RunScript()
	//	}
	//}(serverCtx))

	//统计日活月活 0 1 0 * * *
	c.AddFunc("1 0 * * *", func(svcCtx *svc.ServiceContext) func() {
		return func() {
			logic.NewCronLogic(svcCtx).RunStatistics()
		}
	}(serverCtx))

	c.Start()
}
