// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"script/script/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessLog},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/crontab/run-script",
					Handler: ScriptHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload/script",
					Handler: UploadScriptHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)
}
